language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  #- jruby-19mode # needs jruby compatible deps
before_script:
  - psql -c 'create database deployer_test;' -U postgres
script: "script/ci"
